### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by jglovier** [central-pa-cowork/meta#1]
I'm totes making a logo for this org. JUST so you know.

And it WILL include a keystone.

**Comment by hellohynes** [comment]
Here's an abandoned logo concept from a few years ago. Food for thought.

![Made In PA](https://f.cloud.github.com/assets/1544281/2317150/34390c30-a346-11e3-8e16-8d1bb3e5ad65.png)

**Comment by sroberts** [comment]
I'm Scott Roberts, and I support this Logo!

**Comment by jglovier** [comment]
![cpac-avatar](https://f.cloud.github.com/assets/1319791/2397664/27232582-a9ed-11e3-8a06-b67d442dacff.png)
 :boom:

**Comment by jglovier** [comment]
Also, dat black and white. This would be dope on a t-shirt.

![cpac-avatar-black](https://f.cloud.github.com/assets/1319791/2397669/36ea86ea-a9ed-11e3-8b39-a0b9d491a2b6.png)

**Comment by jglovier** [comment]
Totes game for adding the wording, too, but the avatar alone is pretty fun.

![cpac-tee-blue](https://f.cloud.github.com/assets/1319791/2397709/955d390c-a9ed-11e3-8dc5-9283e95d0735.png)
![cpac-tee](https://f.cloud.github.com/assets/1319791/2397710/955ee4d2-a9ed-11e3-8004-3b39cde26629.png)

**Comment by hellohynes** [comment]
WHO NEEDS WORDS?!?! 

## Nice mark Joel.

Joshua Hynes
hello@joshuahynes.com

**Comment by danthompson** [comment]
Looking slick!

**Comment by danthompson** [comment]
The blue/yellow gives me the old pa license plate feels. I dig.

![image](https://f.cloud.github.com/assets/68388/2397842/2f791528-a9ef-11e3-986d-720500fe8055.png)

![image](https://f.cloud.github.com/assets/68388/2397847/34e5d488-a9ef-11e3-9e02-5af4c06ffa6c.png)

**Comment by lmarburger** [comment]
Badass, @jglovier!

**Comment by jglovier** [comment]
> The blue/yellow gives me the old pa license plate feels.

Oh man. Dat nostagia tho. :heart:
