### ISSUE TITLE
Chat Client?

### ISSUE THREAD

**Issue by hellohynes** [central-pa-cowork/meta#2]
For those moments we aren't together.

**Comment by sroberts** [comment]
I do <3 the Slack

**Comment by joshuamiller** [comment]
I don't feel my gif arsenal is ready to take on you guys in a
slack/hipchat/etc environment.

On Tue, Mar 25, 2014 at 11:35 AM, Scott J. Roberts <notifications@github.com

**Comment by lmarburger** [comment]
(ง •̀_•́)ง

**Comment by lmarburger** [comment]
It's also worth mentioning that [CPLUG](http://cplug.net/wp2/) has an IRC server at irc.cplug.net.

**Comment by sroberts** [comment]
@lmarburger but it's.... _shudder_ IRC.

@joshuamiller As for your GIF game I can only tell you one thing: GET ON THIS LEVEL!
![david bowie - imgur image](https://f.cloud.github.com/assets/44774/2526304/32df4196-b4f9-11e3-95a0-d015e33d249e.gif)

**Comment by hellohynes** [comment]
So is this set up yet?!

**Comment by jglovier** [comment]
Okay, I just setup a Slack account for us. Paste emails here where you want the invite to go to (could have been automatic if we had a domain, but alas, we NO HAZ DOMAIN).

**Comment by jglovier** [comment]
> I don't feel my gif arsenal is ready to take on you guys in a
> slack/hipchat/etc environment.

@joshuamiller here, use mine: http://gifs.joelglovier.com/ :wink:

![aha](http://gifs.joelglovier.com/aha/aha.gif)

**Comment by jglovier** [comment]
@sroberts Bowie FTW. Go home kids.

**Comment by joshuamiller** [comment]
Can't @sroberts just paste all of our emails in here by raiding the db himself?

josh@joshmiller.io

**Comment by hellohynes** [comment]
## hello@joshuahynes.com

Joshua Hynes
hello@joshuahynes.com

**Comment by lmarburger** [comment]
larry@papertrailapp.com

**Comment by danthompson** [comment]
dwthompson@gmail.com

**Comment by hellohynes** [comment]
Thanks for setting this up @jglovier.
