### ISSUE TITLE
Do we want to open this group up to other internet friends?

### ISSUE THREAD

**Issue by hellohynes** [central-pa-cowork/meta#5]
What's our opinion on this?

**Comment by jglovier** [comment]
In what sense? I'm not really opposed, I guess, just don't really understand what you mean.

**Comment by jglovier** [comment]
You mean other local friends who might want to meet up with us, or broader use of "internet friends"?

If the former, then yes, certainly.

**Comment by jglovier** [comment]
Also, of note is that the repo is public, so we can technically just point anyone here and they can get involved. I probably technically made way too many people owners of the group of the actual github org as it is, so not adding more org owners, no.

**Comment by jglovier** [comment]
...but we can add people as "members" who are not "owners".

**Comment by hellohynes** [comment]
@jglovier I mean both.

Local definitely, but also anyone we might know that co-works remotely in different areas too that we think that person's addition to the community would be positive.

Just wondered. 'Tis all.

**Comment by jglovier** [comment]
Personally I'd opt to keep it simple and keep this stuff for people who actually get together with us locally. We have Twitter, Dribbble, Facebook, Google+ (lulz), etc for interacting with the rest of the internet world. :blush: But I'm not strongly opinionated on that, that's just my impression.
